p9/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include("authy.urls")),
    
    path('', include("tikect.urls")),
]

if settings.DEBUG:
    urlpatterns +=static(settings.MEDIA_URL, document_root= settings.MEDIA_ROOT)
    urlpatterns +=static(settings.STATIC_URL, document_root= settings.STATIC_ROOT)

tikect/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('home/', views.home, name="home"),
    path('flux/', views.flux, name="flux"),
    path('flux/<int:page>/', views.flux, name="flux"),
    path('ticket_create/', views.ticket_create, name='ticket_create'),
    path(
        'review_create/',
        views.review_create, name='review_create'),
    path('review_publish/', views.review_publish, name='review_publish'),
    path('posts/', views.posts, name='posts'),
    path('posts/<int:page>/', views.posts, name='posts'),
    path(
        'post_delete/<str:type>/<int:id>/',
        views.post_delete, name='post_delete'),
    path(
        'post_update/<str:type>/<int:id>/',
        views.post_update, name='post_update'),
    path('subscriptions/', views.subscriptions, name='subscriptions'),
    path('unfollow/<int:id>/', views.unfollow, name='unfollow'),

]

tikect/models.py
from PIL import Image

from django.db import models
from django.conf import settings
from django.core.validators import MinValueValidator, MaxValueValidator
from p9 import const



from django.db import models
import uuid
from django.db.models.signals import post_save
from django.conf import settings
from django.urls import reverse
from django.utils.html import mark_safe


RATING = (
    ('0','☆☆☆☆☆'),
    ('1','⭐☆☆☆☆'),
    ('2','⭐⭐☆☆☆'),
    ('3','⭐⭐⭐☆☆'),
    ('4','⭐⭐⭐⭐☆'),
    ('5','⭐⭐⭐⭐⭐'),
)




class Ticket(models.Model):
    type = "ticket"
    title = models.CharField(max_length=128, verbose_name="titre")
    description = models.CharField(max_length=2048, blank=True)
    user = models.ForeignKey(
        settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    image = models.ImageField(blank=True)
    time_created = models.DateTimeField(auto_now_add=True)
    reviewed = models.BooleanField(default=False)

    class Meta:
        ordering = ('-time_created',)

    def resize_image(self):
        if self.image:
            image = Image.open(self.image)
            image.thumbnail(const.IMAGE_MAX_SIZE)
            image.save(self.image.path)

    def save(self, *args, **kwargs):
        super().save(*args, **kwargs)
        self.resize_image()

    def __str__(self):
        return f"{self.title} by {self.user}"


class Review(models.Model):
    type = "review"
    ticket = models.ForeignKey(
        Ticket,
        on_delete=models.CASCADE,
        related_name="review")
    user = models.ForeignKey(
        settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    headline = models.CharField(max_length=128, verbose_name="Titre")
    rating = models.PositiveSmallIntegerField(
        validators=[MinValueValidator(0), MaxValueValidator(5)],
        verbose_name="Note")
    body = models.TextField(
        max_length=8192, blank=True, verbose_name="Commentaire")
    time_created = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return f"{self.ticket} => {self.user}"


class UserFollows(models.Model):
    user = models.ForeignKey(
        settings.AUTH_USER_MODEL,
        on_delete=models.CASCADE,
        related_name="follower")
    followed_user = models.ForeignKey(
        settings.AUTH_USER_MODEL,
        on_delete=models.CASCADE,
        related_name="followed")

    class Meta:
        unique_together = ('user', 'followed_user')

    def __str__(self):
        return f"{self.user} is following {self.followed_user}"

tikect/forms.py
from django import forms
from .models import (
    Ticket,
    Review,
)


"""The forms here are customized to match with the bulma css framework
"""


class TicketNoImageCreateForm(forms.ModelForm):
    title = forms.CharField(
        widget=forms.TextInput(attrs={"class": "input"}),
        label="Titre")
    description = forms.CharField(
        widget=forms.Textarea(attrs={
            "class": "textarea",
            }),
        )

    class Meta:
        model = Ticket
        exclude = ('user', 'image')

    def __init__(self, *args, **kwargs):
        super(TicketNoImageCreateForm, self).__init__(*args, **kwargs)
        # set the value 'required' to false
        self.fields['description'].required = False


class TicketCreateForm(TicketNoImageCreateForm):
    image = forms.ImageField(
        widget=forms.FileInput(attrs={
            "type": "file",
        })
    )

    class Meta:
        model = Ticket
        exclude = ('user',)


class ReviewCreateForm(forms.ModelForm):
    headline = forms.CharField(
        widget=forms.TextInput(attrs={"class": "input"}),
        label="Titre")
    body = forms.CharField(
        widget=forms.Textarea(attrs={
            "class": "textarea",
            }),
        label="Commentaire",
        )
    CHOICES = [
        ('0', '- 0'), ('1', '- 1'), ('2', '- 2'),
        ('3', '- 3'), ('4', '- 4'), ('5', '- 5')]
    rating = forms.ChoiceField(
        widget=forms.RadioSelect, choices=CHOICES,
        label="Note")

    class Meta:
        model = Review
        exclude = ('user', 'ticket',)


class SearchForm(forms.Form):
    entry = forms.CharField(
        max_length=150,
        widget=forms.TextInput(
            attrs={
                "class": "input",
                "placeholder": "Nom d'utilisateur",
                },
            ),
        )

tikect/views.py
from itertools import chain

from django.core.paginator import Paginator, EmptyPage
from django.http import Http404
from django.shortcuts import redirect, render, get_object_or_404
from django.contrib import messages
from django.contrib.auth import get_user_model
from django.contrib.auth.decorators import login_required
from django.db.models import Q

from .models import (
    Ticket,
    Review,
    UserFollows,
)
from .forms import (
    TicketCreateForm,
    TicketNoImageCreateForm,
    ReviewCreateForm,
    SearchForm,
)
from p9 import const


def home(request):
    """This view is displayed by default,
    even if a user is not connected"""
    return render(request, 'tikect/home.html')


@login_required
def flux(request, page=1):
    followed_users = get_user_model().objects.filter(
        followed__user=request.user)
    reviews = Review.objects.filter(
        Q(user=request.user) | Q(ticket__user=request.user) |
        Q(user__in=followed_users))
    tickets = Ticket.objects.filter(
        Q(user=request.user) | Q(user__in=followed_users))

    posts_created = sorted(
        chain(
            reviews,
            tickets,
            ),
        key=lambda post: post.time_created, reverse=True)
    paginator = Paginator(posts_created, 3)
    try:
        posts = paginator.page(page)
    except EmptyPage:
        posts = paginator.page(paginator.num_pages)

    context = {
        "posts": posts,
    }
    return render(request, "tikect/flux.html", context)


@login_required
def ticket_create(request):
    if request.method == "POST":
        if len(request.FILES) == 0:
            form = TicketNoImageCreateForm(request.POST)
        else:
            form = TicketCreateForm(request.POST, request.FILES)
        if form.is_valid():
            ticket = form.save(commit=False)
            ticket.user = request.user
            ticket.reviewed = True
            ticket.save()
            return redirect('flux')
    form = TicketCreateForm()
    context = {
        "form": form,
    }
    return render(request, "tikect/ticket_create.html", context)


@login_required
def review_create(request, ticket_id):
    """Creates a review from an existing ticket"""
    ticket = get_object_or_404(Ticket, id=ticket_id)
    if ticket.reviewed:
        raise Http404()
    if request.method == "POST":
        form = ReviewCreateForm(request.POST)
        if form.is_valid():
            review = form.save(commit=False)
            review.ticket = ticket
            review.user = request.user
            review.save()
            ticket.reviewed = True
            ticket.save()
            return redirect('flux')

    form = ReviewCreateForm()
    context = {
        "ticket": ticket,
        "form": form,
    }
    return render(request, "tikect/review_create.html", context)


@login_required
def review_publish(request):
    """Creates a spontaneous review without ticket, the ticket is
    genereted beside the review in a row"""
    if request.method == "POST":
        ticket_form = TicketCreateForm(request.POST, request.FILES)
        review_form = ReviewCreateForm(request.POST)
        if ticket_form.is_valid() and review_form.is_valid():
            ticket = ticket_form.save(commit=False)
            ticket.user = request.user
            ticket.save()

            review = review_form.save(commit=False)
            review.ticket = ticket
            review.user = request.user
            review.save()
            ticket.reviewed = True
            ticket.save()
            return redirect('flux')

    ticket_form = TicketCreateForm()
    review_form = ReviewCreateForm()
    context = {
        'ticket_form': ticket_form,
        'review_form': review_form,
    }
    return render(request, "tikect/review_publish.html", context)


@login_required
def subscriptions(request):
    """this views allows to follow / unfollow other users"""
    followings = UserFollows.objects.filter(user=request.user)
    followers = UserFollows.objects.filter(followed_user=request.user)
    if request.method == "POST":
        form = SearchForm(request.POST)
        if form.is_valid():
            name = form.cleaned_data['entry']
            try:
                user_to_follow = get_user_model().objects.get(username=name)
            except get_user_model().DoesNotExist:
                messages.add_message(
                    request, messages.ERROR, (
                        f"Il n'existe pas d'utilisateur \"{name}\""
                        ),
                    extra_tags=const.ERROR
                )
                return redirect('subscriptions')
            else:
                new_follow = UserFollows(
                    user=request.user, followed_user=user_to_follow)
                new_follow.save()
                messages.add_message(
                    request, messages.SUCCESS, (
                        f"Vous êtes abonné à \"{name}\""
                        ),
                    extra_tags=const.SUCCESS
                )
                return redirect('subscriptions')

    form = SearchForm()
    context = {
        'followings': followings,
        'followers': followers,
        'form': form,
    }
    return render(request, 'tikect/subscriptions.html', context)


@login_required
def unfollow(request, id):
    """This code is called to unfollow a user when the button
    "unsuscribe" is clicked"""
    unfollow = get_object_or_404(get_user_model(), id=id)
    if request.method == "POST":
        unfollowing = get_object_or_404(
            UserFollows, user=request.user, followed_user=unfollow)
        unfollowing.delete()
        messages.add_message(
            request, messages.SUCCESS, (
                f"Vous vous êtes désabonné à \"{unfollow.username}\""
                ),
            extra_tags=const.SUCCESS
        )
        return redirect('subscriptions')

    context = {
        "unfollow": unfollow,
    }
    return render(request, 'tikect/unfollow.html', context)


@login_required
def posts(request, page=1):
    "displays the own posts of a user"
    reviews = request.user.get_reviews()
    tickets = request.user.get_tickets()
    posts_created = sorted(
        chain(
            reviews,
            tickets,
            ),
        key=lambda post: post.time_created, reverse=True)
    paginator = Paginator(posts_created, 3)
    try:
        posts = paginator.page(page)
    except EmptyPage:
        posts = paginator.page(paginator.num_pages)
    context = {
        'posts': posts,
    }
    return render(request, "tikect/posts.html", context)


@login_required
def post_delete(request, type, id):
    if type == 'review':
        post = get_object_or_404(Review, id=id)
        request.user.is_user(post)
        ticket = post.ticket
        ticket.reviewed = False
        ticket.save()
    elif type == 'ticket':
        post = get_object_or_404(Ticket, id=id)
    else:
        raise Http404()
    if request.method == "POST":
        post.delete()
        request.user.is_user(post)
        return redirect('posts')
    context = {
        'post': post,
        'type': type,
    }
    request.user.is_user(post)
    return render(request, 'tikect/post_delete.html', context)


@login_required
def post_update(request, type, id):
    if request.method == "POST":
        if type == 'review':
            post = get_object_or_404(Review, id=id)
            request.user.is_user(post)
            form = ReviewCreateForm(request.POST, instance=post)
            if form.is_valid():
                form.save()
        elif type == 'ticket':
            post = get_object_or_404(Ticket, id=id)
            request.user.is_user(post)
            form = TicketCreateForm(
                request.POST, request.FILES, instance=post)
            reviewed = post.reviewed
            if form.is_valid():
                ticket = form.save(commit=False)
                ticket.reviewed = reviewed
                ticket.save()
        else:
            raise Http404()
        return redirect('posts')

    if type == 'review':
        post = get_object_or_404(Review, id=id)
        form = ReviewCreateForm(instance=post)

    elif type == 'ticket':
        post = get_object_or_404(Ticket, id=id)
        form = TicketCreateForm(instance=post)
    else:
        raise Http404()

    context = {
        'post': post,
        'form': form,
        'type': type,
    }
    request.user.is_user(post)
    return render(request, 'tikect/post_update.html', context)

tikect/templates/tikect/__review_form.html
<strong>{{ form.headline.label }}</strong>
<strong>{{ form.headline }}</strong>
<strong>{{ form.rating.label }}</strong><br>
<div class="columns">
    {% for choice in form.rating %}
        <div class="column">
            <span>{{choice.label}}  {{choice}}</span>
        </div>
    {% endfor %}

</div>

<br>
<strong>{{ form.body.label }}</strong>
{{ form.body }}

tikect/templates/tikect/__ticket.html
<p>
    {% if ticket.user == user %}
    Vous avez
    {% else %}
    {{ticket.user}} a
    {% endif %} demandé une critique <span class="is-pulled-right">{{ ticket.time_created }}</span></p>
    <br>
    <p>{{ticket.title}}</p>
    <p>{{ticket.description}}</p>
    {% if ticket.image %}
        <img src="{{ ticket.image.url }}" alt="cover" class="cover m-5">
    {% endif %}



    {% if buttons == 'ticket_buttons' %}
    <div>
        <a href="{% url 'post_delete' 'ticket' ticket.id %}" class="button is-danger is-pulled-right ml-5">Supprimer</a>
        <a href="{% url 'post_update' 'ticket' ticket.id %}" class="button is-pulled-right">Modifier</a>

    </div>
    <div style="height:40px"></div>
    {% elif buttons == 'no_buttons' %}

    {% else %}

        {% if not buttons == 'no_buttons' %}
            {% if not ticket.reviewed %}
            <div>
                <a href="{% url 'review_create'  ticket.id  %}" class="button is-pulled-right">Créer une critique</a>
            </div>
            <div style="height:30px"></div>
            {% else %}
            <div style="height:10px"></div>
            {% endif %}
        {% endif %}
    {% endif %}

tikect/templates/tikect/__ticket_form.html
<div class="field">
    <label class="label">{{ form.title.label }}</label>
    <div class="control">
        {{ form.title }}
    </div>

</div>

<div class="field">
    <label class="label">{{ form.description.label }}</label>
    <div class="control">
        {{ form.description }}
    </div>
</div>

<label class="label">{{ form.image.label }}</label>
{% if image %}
    <img src="{{ image }}" alt="cover" class="cover m-5">
{% endif %}
<div class="file">
    <label class="file-label">
      <input id="id_image" class="file-input" type="file" name="image" accept="image/*">
      <span class="file-cta">
        <span class="file-icon">
            <span class="material-icons">
                file_upload
            </span>
        </span>
            <span class="file-label">
                Télécharger un fichier
            </span>
      </span>
      <span class="file-name is-fullwidth" id="selected_file" title="aucun fichier">
        aucun fichier selectionné
      </span>
    </label>

  </div>



{% block script %}
<script>

const fileInput = document.getElementById('id_image');
const selected_file_elem = document.getElementById('selected_file')
fileInput.onchange = () => {
const selectedFile = fileInput.files[0];
selected_file_elem.innerHTML = selectedFile.name;
selected_file_elem.setAttribute("title", selectedFile.name);

}
</script>

{% endblock script %}

tikect/templates/tikect/flux.html
{% extends 'base.html' %}

{% load static %}

{% block content %}

<div class="columns is-centered">
    <div class="column is-half">
        <div class="columns m-5">
            {% include 'pagination.html' with view_name='flux' objects=posts%}
        </div>
        <div class="columns" >
            <div class="column is-half">
                <a class="button is-fullwidth" href="{% url 'ticket_create' %}">Demander une critique</a>
            </div>
            <div class="column is-half">
                <a class="button is-fullwidth" href="{% url 'review_publish' %}">Créer une critique</a>
            </div>
        </div>
    </div>
</div>

<section class="columns is-centered">
    <div class="column is-half">

    {% for post in posts %}
    <article class="box m-5">
        {% if post.type == "ticket" %}
            {% include 'tikect/ticket.html' with ticket=post user=user %}
        {% elif post.type == "review" %}
            {% include 'tikect/review.html' with review=post user=user %}
        {% endif %}

    </article>
    <div class="do-up">
        <a href="#">
            <span class="material-icons is-pulled-left">
                arrow_upward
            </span>
        </a>
    </div>
    {% endfor %}
    </div>

</section>

{% endblock content %}


{% block script %}
<script type="text/javascript" src="{% static 'tikect/js/stars.js' %}"></script>
{% endblock script %}

tikect/templates/tikect/post_update.html
{% extends 'base.html' %}

{% block content %}
<div class="columns is-centered">
    <div class="column is-half">
        <h1 class="subtitle">Modifier votre post</h1>
            {% if type == 'review' %}
            <div class="box p-5">
                <h2 class="subtitle">Vous êtes en train de poster en reponse à</h2>
                <div class="box m-5">
                    <p>{{post.ticket.user}} a demandé une critique <span class="is-pulled-right">{{ post.ticket.time_created }}</span></p>
                    <br>
                    <p>{{post.ticket.title}}</p>
                    <p>{{post.ticket.description}}</p>
                    {% if post.ticket.image %}
                        <img src="{{ post.ticket.image.url }}" alt="cover" class="cover m-5">
                    {% endif %}
                </div>
            </div>
            {% endif %}


        <form action="" method="post" enctype="multipart/form-data">
            {% csrf_token %}
            {% if type == "ticket" %}
                {% include 'tikect/ticket_form.html' with image=post.image.url buttons='no_buttons' %}
            {% elif type == "review" %}
                {% include 'tikect/review_form.html' %}
            {% endif %}


            <button class="button is-primary mt-5 is-pulled-right">Envoyer</button>
        </form>
    </div>
</div>




{% endblock content %}

tikect/templates/tikect/review.html
<p>
    {% if review.user == user %}
    Vous avez
    {% else %}
    {{review.user}} a
    {% endif %} publié une critique <span class="is-pulled-right">{{ review.time_created }}</span></p>
    <br>
    <p>{{review.headline}} - <span class="rating" id="rating_id_{{review.id}}" rating="{{ review.rating }}"></span></p>
    <p>{{review.body}}</p>

    <article class="box m-5">
        {% include 'tikect/ticket.html' with ticket=review.ticket buttons='no_buttons' %}
    </article>

    {% if buttons == 'review_buttons' %}
    <a href="{% url 'post_delete' 'review' review.id %}" class="button is-danger is-pulled-right ml-5">Supprimer</a>
    <a href="{% url 'post_update' 'review' review.id %}" class="button is-pulled-right">Modifier</a>
    <div style="height:40px"></div>
    {% else %}
    <div style="height:10px"></div>
    {% endif %}

tikect/templates/tikect/review_create.html
{% extends 'base.html' %}
{% block content %}
    <h2>Créer une critique</h2>
    <form class="posting-form" method="post" enctype="multipart/form-data">
        <div>
            <h2>Livre/Article:</h2>
        <p>
            <label for="{{ ticket_form.title.label }}">Titre&nbsp;:</label>
            <br>
            {{ ticket_form.title }}
        </p>
        <p>
            <label for="{{ ticket_form.description.label }}">Description&nbsp;:</label>
            <br>
            {{ ticket_form.description }}
        </p>
        <p>
            <label>Image:</label>
            <br>
            <label>
                <span for="{{ticket_form.image.label}}" class="btn btn--edit">Télécharger</span>
                {{ ticket_form.image }}
            </label>
            {{ ticket_form.edit_ticket }}
        </p>
        </div>
        <div>
            <h2>Critique:</h2>
            {{ review_form.as_p }}
            {% csrf_token %}
            <div class="bloc__post">
                <button type="submit">Publier</button>
            </div>
        </div>

    </form>
{% endblock content %}

tikect/templates/tikect/review_form.html
<strong>{{ form.headline.label }}</strong>
<strong>{{ form.headline }}</strong>
<strong>{{ form.rating.label }}</strong><br>
<div class="columns">
    {% for choice in form.rating %}
        <div class="column">
            <span>{{choice.label}}  {{choice}}</span>
        </div>
    {% endfor %}

</div>

<br>
<strong>{{ form.body.label }}</strong>
{{ form.body }}

tikect/templates/tikect/review_publish.html
{% extends 'base.html' %}

{% block content %}
<div class="columns is-centered">
    <div class="column is-half">
        <h1 class="subtitle">Créer une critique</h1>
        <div class="box">
            <form action="" method="post" enctype="multipart/form-data">
                {% csrf_token %}
                <h1 class="subtitle">Livre/article</h1>
                {% include 'tikect/ticket_form.html' with form=ticket_form %}
                <hr>
                <h1 class="subtitle">Critique</h1>
                {% include 'tikect/review_form.html' with form=review_form %}

                <button class="button is-pulled-right mt-5">Envoyer</button>
                <div style="height: 50px"></div>
            </form>

        </div>

    </div>

</div>

{% endblock content %}

tikect/templates/tikect/review_with_ticket.html
{% extends 'base.html' %}

{% block content %}
<div class="columns is-centered">
    <div class="column is-half">
        <h1 class="subtitle">Créer une critique</h1>
        <div class="box">
            <form action="" method="post" enctype="multipart/form-data">
                {% csrf_token %}
                <fieldset>
                    <legend><h1 class="subtitle">Livre/article</h1></legend>
                    <h6>Titre</h6>
                    {{ticket_form.title}}
                    <h6>Description</h6>
                  {{ticket_form.description}}
                  <p>Image</p> 
                    <div class="file">
                        <label class="file-label">
                          {{ticket_form.image}}
                          <span class="file-cta">
                            <span class="file-icon">
                              <i class="fas fa-upload"></i>
                            </span>
                            <span class="file-label">
                                Télécharger ﬁchier
                            </span>
                          </span>
                        </label>
                    </div>
                </fieldset>
                
                
                <hr>

                <fieldset>
                    <legend><h1 class="subtitle">Critique</h1></legend>
                    
                    <strong>{{ review_form.headline.label }}</strong>
                    <strong>{{ review_form.headline }}</strong>
                    <strong>{{ review_form.rating.label }}</strong><br>

                    <div class="select is-medium">
                        <select name="{{review_form.rating.html_name}}" required>
                            <option value="selected disabled">Selectionnez une note</option>
                            {% for value, label in review_form.rating.field.choices %}
                            <option value="{{value}}">
                              <span>{{label}}  </span>
                            </option>
                            {% endfor %}                                                
                        </select>
                      </div>
                 
                        <br>
                    <strong>{{ review_form.description.label }}</strong>
                    {{ review_form.description }}
                </fieldset>
                
                

                <button class="button is-pulled-right mt-5">Envoyer</button>
                <div style="height: 50px"></div>
            </form>

        </div>

    </div>

</div>

{% endblock content %}

tikect/templates/tikect/ticket.html
<p>
    {% if ticket.user == user %}
    Vous avez
    {% else %}
    {{ticket.user}} a
    {% endif %} demandé une critique <span class="is-pulled-right">{{ ticket.time_created }}</span></p>
    <br>
    <p>{{ticket.title}}</p>
    <p>{{ticket.description}}</p>
    {% if ticket.image %}
        <img src="{{ ticket.image.url }}" alt="cover" class="cover m-5">
    {% endif %}



    {% if buttons == 'ticket_buttons' %}
    <div>
        <a href="{% url 'post_delete' 'ticket' ticket.id %}" class="button is-danger is-pulled-right ml-5">Supprimer</a>
        <a href="{% url 'post_update' 'ticket' ticket.id %}" class="button is-pulled-right">Modifier</a>

    </div>
    <div style="height:40px"></div>
    {% elif buttons == 'no_buttons' %}

    {% else %}

        {% if not buttons == 'no_buttons' %}
            {% if not ticket.reviewed %}
            <div>
                <a href="{% url 'review_create'  ticket.id  %}" class="button is-pulled-right">Créer une critique</a>
            </div>
            <div style="height:30px"></div>
            {% else %}
            <div style="height:10px"></div>
            {% endif %}
        {% endif %}
    {% endif %}

tikect/templates/tikect/ticket_create.html
{% extends 'base.html' %}

{% block content %}

<section class="columns is-centered">
    <div class="column is-half">
        <h1 class="title">Creer un ticket</h1>
        <form action="" method="post" enctype="multipart/form-data">
            {% csrf_token %}

            {% include 'tikect/ticket_form.html' %}

            <br>
            <input type="submit" value="Envoyer" class="button is-primary is-pulled-right">
        </form>
    </div>

</section>

{% endblock content %}

tikect/templates/tikect/ticket_form.html
<div class="field">
    <label class="label">{{ form.title.label }}</label>
    <div class="control">
        {{ form.title }}
    </div>

</div>

<div class="field">
    <label class="label">{{ form.description.label }}</label>
    <div class="control">
        {{ form.description }}
    </div>
</div>

<label class="label">{{ form.image.label }}</label>
{% if image %}
    <img src="{{ image }}" alt="cover" class="cover m-5">
{% endif %}
<div class="file">
    <label class="file-label">
      <input id="id_image" class="file-input" type="file" name="image" accept="image/*">
      <span class="file-cta">
        <span class="file-icon">
            <span class="material-icons">
                file_upload
            </span>
        </span>
            <span class="file-label">
                Télécharger un fichier
            </span>
      </span>
      <span class="file-name is-fullwidth" id="selected_file" title="aucun fichier">
        aucun fichier selectionné
      </span>
    </label>

  </div>



{% block script %}
<script>

const fileInput = document.getElementById('id_image');
const selected_file_elem = document.getElementById('selected_file')
fileInput.onchange = () => {
const selectedFile = fileInput.files[0];
selected_file_elem.innerHTML = selectedFile.name;
selected_file_elem.setAttribute("title", selectedFile.name);

}
</script>

{% endblock script %}

tikect/templates/tikect/unfollow.html
{% extends 'base.html' %}

{% block content %}

<div class="has-text-centered mt-50">
    <section classs="">
        <h1 class="subtitle">Êtes-vous certain de ne plus suivre {{unfollow.username}} ?</h1>

        <form action="" method="post">
            {% csrf_token %}
            <a href="{% url 'subscriptions' %}" class="button">Annuler</a>
            <button class="button is-danger">Me désabonner</button>
        </form>
    </section>

</div>

{% endblock content %}